### ISSUE TITLE
Funciones `and` y `or` diferentes a las pedidas.

### ISSUE THREAD

**Issue by fidel-ml** [aguirrediego32/EstrD22s1#1]
La función `and` de la práctica 1 debería comportarse de la siguiente manera:
```
> and False (error "Mal")
False
```
Sin embargo, tu versión da `error "Mal"`.
Así, no es la función pedida.

Exactamente lo mismo pasa con la función `or`, que debería pasar el test `or True (error "Mal")` dando `True`.

**Comment by fidel-ml** [comment]
Vimos en clase que si bien funciona, el doble PM no es demasiado feliz. ¿Podés hacerlas sin recurrir al doble PM?

**Comment by aguirrediego32** [comment]
Buenas noches perdón la demora, subo las correcciones.
