### ISSUE TITLE
La función `unoOCero` tiene demasiadas responsabilidades y su nombre no es feliz

### ISSUE THREAD

**Issue by fidel-ml** [aguirrediego32/EstrD22s1#10]
Es uno o cero ¿en qué casos? Por otra parte, podés separarla en dos funciones, cada una de las cuales haga la parte que le toca (y así, conservando el nombre `unoOCero` para esta función, o uno similar (mejor es el visto en Intro...)

**Comment by aguirrediego32** [comment]
Modifico el código de unoOCero en 2 partes.
