### ISSUE TITLE
Pr2: la segunda ecuación de `concatenar` es innecesaria

### ISSUE THREAD

**Issue by fidel-ml** [aguirrediego32/EstrD22s1#11]
NO tenés que mirar más de un argumento NUNCA, a menos que sea imposible hacerlo de otra manera. 
Cuando lo hacés, estás garantizando o bien que vas a perder casos, o bien que vas a tener casos de más y consecuentemente tener más chances de error. Además, trabajás de más, lo que nunca es feliz...

**Comment by aguirrediego32** [comment]
Perfecto, me confundí cuando interprete lo que entendí por  subcaso. Entonces : 
concatenar (caso base)  --- > [ ] ys 
concatenar  (caso recursivo )--->   (x:xs) (y:ys)
concatenar xs [ ]    <---- (este es el argumento que no hace falta analizar)

**Comment by fidel-ml** [comment]
No. Hay solamente DOS casos `concatenar [] ys` y `concatenar (x:xs) ys`. NO necesitás mirar el 2do argumento en ningún momento. NUNCA hagas PM para algo que todavía no sabés si necesitás.

**Comment by aguirrediego32** [comment]
Ok, gracias por por la explicación.
