### ISSUE TITLE
Pr2: en `totalGanador` solamente mirás el tipo para saber si gana...

### ISSUE THREAD

**Issue by fidel-ml** [aguirrediego32/EstrD22s1#12]
Básicamente, estás haciendo que esa función dependa del significado de ganar. Si luego lo queremos cambiar para que los Pokémon peleen más allá de su tipo (por ejemplo, por nivel), entonces esta función deja de andar. Siempre es bueno que las responsabilidades queden acotadas a las funciones que les corresponden. En este caso, contar cuántos ganan es cuestión de contar, y no de saber cómo pelean. Deberías utilizar una función que dados 2 Pokémon diga cuál gana...

**Comment by aguirrediego32** [comment]
No estoy pudiendo cambiar el ejercicio. Entiendo que la solución totalGanador tiene que contar nada mas, pero la función leGanaATodos me indica si lo cuento o no. O te referís que tengo que cambiar la función  superaA y  leGanaATodos porque uso TipoDePokemon y Pokemon en lugar de Pokemon y Pokemon.

**Comment by fidel-ml** [comment]
Ahora la veo bien. No sé qué quise decir... :D
