### ISSUE TITLE
Pr 2: la función `cantidadTotal` es un renombre innecesario

### ISSUE THREAD

**Issue by fidel-ml** [aguirrediego32/EstrD22s1#16]
En general no es feliz tener funciones que se limitan a cambiarle el nombre a otra sin aportar nada propio (como un cambio de nivel de abstracción). Podrías haber usado `longitud` directamente en la función `cantQueTrabajanEn`.

**Comment by aguirrediego32** [comment]
Ok, no se porque pensé que era mas claro  si lo hacía de ese modo. Ahora lo cambio.
