### ISSUE TITLE
Pr2: en `cuentaRegresiva` no tenés en cuenta los valores negativos

### ISSUE THREAD

**Issue by fidel-ml** [aguirrediego32/EstrD22s1#18]
El enunciado pide explícitamente que se contemplen, pues establece que NO debe ser un error. Así como está definida, los números negativos se cuelgan.

**Comment by aguirrediego32** [comment]
Ok, hice una solución pero no estoy seguro si es la correcta porque el caso base "estaría de mas" , por eso dudo de mi solución.
cuentaRegresiva :: Int -> [Int]
--cuentaRegresiva 0 = [] <-- esta
cuentaRegresiva n = if (n < 1)
                        then []
                        else n : cuentaRegresiva (n - 1)

**Comment by fidel-ml** [comment]
Exacto. El caso base queda incluído en la rama del then.
