### ISSUE TITLE
Pr2: en la función `asignadosPorProyecto` estás repitiendo muchas veces cada proyecto...

### ISSUE THREAD

**Issue by fidel-ml** [aguirrediego32/EstrD22s1#19]
O sea, si un proyecto p particular aparece 3 veces, ponés 3 elementos (p,3) en la lista final, y esto no es feliz.
Además, estás recorriendo muchísimas veces todos los proyectos de la empresa, lo que no es muy bueno.
La idea es usar recursión estructural sobre los proyectos de la empresa...

**Comment by aguirrediego32** [comment]
No logro entender como hacer mas eficiente la solución. El ejercicio pide que devuelva una lista de pares con la cantidad de personas involucradas en los proyectos, si un proyecto apareces 3 veces entiendo que es porque hay 3 personas involucradas. Entonces yo reutilice la primera función "proyectos" que devuelve los proyectos de la empresa sin repetidos en una función auxiliar en la que arma el par con cada proyecto de la lista y los roles de la empresa. También uso la función rolesEmpresa que da una lista con todos los empleados.

**Comment by fidel-ml** [comment]
Ah, leí al revés. Sin embargo, lo que hacés entonces es recorrer, por cada proyecto TODOS los roles.
Lo que no tenés que hacer es duplicar la información. Para generar esos proyectos sin repetir estás recorriendo todo muchas veces. Y LUEGO con esos, VOLVÉS a recorrer todo PARA CADA PROYECTO, para contarlo. Es MUCHO trabajo de más.

La idea es usar recursión estructural sobre los roles... ;) No dupliques información. Simplemente usá recursión estructural. Después de todo, es una práctica de recursión estructural.

**Comment by aguirrediego32** [comment]
Subo la corrección de este ejercicio.

**Comment by fidel-ml** [comment]
Mucho mejor. Pero estás recorriendo para ver si está, y si está, volvés a recorrer para incrementar la cantidad. Podrías resolverlo si hacés una única recorrida, y si lo encontrás le sumás y si no, lo agregás AL FINAL...

**Comment by aguirrediego32** [comment]
Perdón por la demora, subo el ejercicio.
