### ISSUE TITLE
Pr3: `alMenosNTesoros` trabaja de más

### ISSUE THREAD

**Issue by fidel-ml** [aguirrediego32/EstrD22s1#23]
Estás reemplazando una búsqueda por una totalización, y eso no es bueno. Lo vieron en InPr con la búsqueda del ancho de espadas: si tengo 10mil cartas, y el ancho está primero, si trato de contar los anchos tengo que mirar las 10mil cartas, pero puedo cortar apenas veo esa carta y no necesito mirarlas todas...

**Comment by aguirrediego32** [comment]
Ok, voy a pensar otra estrategia, gracias por la pista.
