### ISSUE TITLE
Pr3: `cantTesorosEn` podría usar menos ecuaciones y tener un nombre más adecuado

### ISSUE THREAD

**Issue by fidel-ml** [aguirrediego32/EstrD22s1#24]
Tenés 3 ecuaciones para cubrir el caso 0, cuando podrías solucionarlo directamente con una subtarea que exprese esos casos...
Además, el nombre de la función no es totalmente adecuado, porque "En" da la idea de un único lugar.

**Comment by aguirrediego32** [comment]
Ok, subo la corrección.
