### ISSUE TITLE
Pr3: faltan funciones 

### ISSUE THREAD

**Issue by fidel-ml** [aguirrediego32/EstrD22s1#27]
A saber:
  * `eval`
  * `simplificar`

**Comment by aguirrediego32** [comment]
Si, subí los que tenía hechos, ahora los completo.

**Comment by fidel-ml** [comment]
Las funciones de `simplificarX` no funcionan como se espera, porque miran de más en los casos especiales... ¿Por qué solamente sacás los 0 que vayan con un Valor? Así, si hago (0+(2+3)) no lo sacás.

**Comment by aguirrediego32** [comment]
Entiendo, me estaba fijando solo en el caso de Valor y no en cualquier ExpA. Subo la corrección.

**Comment by aguirrediego32** [comment]
Subo la corrección.
