### ISSUE TITLE
Pr3: `tesorosEntre` tiene un nombre inadecuado

### ISSUE THREAD

**Issue by fidel-ml** [aguirrediego32/EstrD22s1#28]
¿Entre qué? Si es desde el comienzo y hasta el número de pasos dados...

**Comment by aguirrediego32** [comment]
Subo la corrección.

**Comment by aguirrediego32** [comment]
Subo la corrección.

**Comment by fidel-ml** [comment]
Ojo que no estás considerando los índices negativos...
