### ISSUE TITLE
Pr3: en `cantTesorosEntre` faltan casos

### ISSUE THREAD

**Issue by fidel-ml** [aguirrediego32/EstrD22s1#30]
Así como está, es parcial, y debería ser total...
¿Sobre qué estás haciendo recursión? ¿Usaste la técnica de recursión estructural?

**Comment by aguirrediego32** [comment]
Subo la corrección.

**Comment by fidel-ml** [comment]
Siguen faltando casos. Tenés que pensar qué casos cubre cada uno. Para no perderte, sirve usar el esquema de recursión sobre un parámetro, y cuando es necesario, separar ese caso según el esquema de recursión de otro parámetro, etc.

**Comment by aguirrediego32** [comment]
Subo la corrección.
