### ISSUE TITLE
En la práctica 1, hay "miedo al booleano" en la función or

### ISSUE THREAD

**Issue by fidel-ml** [aguirrediego32/EstrD22s1#7]
En la función `or` estás haciendo una versión con pattern matching del "miedo al booleano".
Básicamente, preguntás si algo es `True` para devolver `True` y cuando no es `True` devolvés `False`. Está escondida debido al uso de guiones bajos sin pensar demasiado... :-D
Básicamente, es como si tuvieses `if b==True then True else False`, que es exactamente lo mismo que `b`.

**Comment by fidel-ml** [comment]
Ahora la función tiene doble PM. Como hablamos en clase, el doble PM es una característica que hay que evitar en la medida de lo posible. ¿Podés hacer `and` y `or` sin doble PM?

**Comment by aguirrediego32** [comment]
Ya entendí el error de hacer doble PM , ya realizo la corrección.
